# docker-compose file for main (production) branch

version: '3.7'

services:
  weatherCol-app:
    image: weathercol-image-prod
    build: .     
          
    ports:
      - 8000:8000
      
    env_file:
      - env-vars-prod.env
    

    container_name: weatherCol-app-prod
