version: '3.7'

services:
  weathercol-app:    
    build: .     
          
    expose:
      - 8000
      
    env_file:
      - .env-vars-prod.env

    restart: unless-stopped

    networks:
      - weatherCol-app_network

    container_name: "weatherCol-app_web"
  
  nginx:
    # location of nginx's Dockerfile
    build: ./nginx/
    
    depends_on:
      - "weathercol-app"

    volumes:
      - ./public:/var/www/weatherCol-app/public/

    restart: unless-stopped

    networks:
      - weatherCol-app_network
    
    container_name: "weatherCol-app_nginx"

  weathercol-app_tunnel:
    # cloudflare tunnel
    image: cloudflare/cloudflared:1449-569a7c3c9ed0

    env_file:
      - .env-vars-prod.env    

    command: tunnel --no-autoupdate run

    restart: unless-stopped
      
    networks:
      - weatherCol-app_network

    container_name: "weatherCol-app_tunnel"

networks:
  weatherCol-app_network:
    external: true
